### PR TITLE
Wikia patch

### PR DESCRIPTION
**Pull request by ljagiello**
* go fmt on all *.go files
* part size bump 5MB -> 512MB
* concurrency bump 5 -> 10

### CODE REVIEW

**Comment by koblas** [comment]
While I see you pulled the patch, you did prompt me to `go fmt` everything since it was overlooked.

**Comment by ljagiello** [comment]
@koblas sorry about that I was going to push some changes to our fork but I'm happy to make a PR here if you want.

**Comment by koblas** [comment]
No problem.  

The only two things I didn't address from the PR that you had were the Makefile changes and the UploaderWithClient parameter changes. 

Would the concurrency/partsize be worth adding as a configuration parameter?

Also, is there any other changes that you've got that would be useful?

**Comment by ljagiello** [comment]
Oh yeah I already moved that to configuration (probably needs a bit of polishing - https://github.com/Wikia/s3-cli). Besides concurrency/part size important for our use case was also ability to control storage class (we sometimes want to use reduced redundancy)

**Comment by koblas** [comment]
Polishing completed, let me know if you see anything else.

**Pull request closed without merging**
